//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixieCursors.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PixieCursors.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A.
        /// </summary>
        public static string A_pply {
            get {
                return ResourceManager.GetString("A_pply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About:.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Swatch.
        /// </summary>
        public static string AddSwatch {
            get {
                return ResourceManager.GetString("AddSwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ancel.
        /// </summary>
        public static string ancel {
            get {
                return ResourceManager.GetString("ancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply Shadow.
        /// </summary>
        public static string ApplyShadow {
            get {
                return ResourceManager.GetString("ApplyShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App to create your own custom cursors - v1.4.1.
        /// </summary>
        public static string AppToCreateYourOwnCustomCursors {
            get {
                return ResourceManager.GetString("AppToCreateYourOwnCustomCursors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 🢔🢔   Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Background Transparency.
        /// </summary>
        public static string BackgroundTransparency {
            get {
                return ResourceManager.GetString("BackgroundTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brush (B).
        /// </summary>
        public static string Brush {
            get {
                return ResourceManager.GetString("Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C.
        /// </summary>
        public static string C_ancel {
            get {
                return ResourceManager.GetString("C_ancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ColorPicker (I).
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ColorPicker.
        /// </summary>
        public static string ColorPickerTitle {
            get {
                return ResourceManager.GetString("ColorPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to create a new file? Your changes will be lost..
        /// </summary>
        public static string CreateAnotherFile {
            get {
                return ResourceManager.GetString("CreateAnotherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crop Empty Margin.
        /// </summary>
        public static string CropEmptyMargin {
            get {
                return ResourceManager.GetString("CropEmptyMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cursors Folder.
        /// </summary>
        public static string CursorsFolder {
            get {
                return ResourceManager.GetString("CursorsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Double click to replace all pixels with the same color.
        /// </summary>
        public static string DoubleClickToReplaceAllPixels {
            get {
                return ResourceManager.GetString("DoubleClickToReplaceAllPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hold down Shift and click to draw a line.
        /// </summary>
        public static string DrawLine {
            get {
                return ResourceManager.GetString("DrawLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eraser (E).
        /// </summary>
        public static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fill (F).
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flip Horizontal.
        /// </summary>
        public static string FlipHorizontal {
            get {
                return ResourceManager.GetString("FlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flip Vertical.
        /// </summary>
        public static string FlipVertical {
            get {
                return ResourceManager.GetString("FlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folder doesn&apos;t exists.
        /// </summary>
        public static string FolderDoesnTExists {
            get {
                return ResourceManager.GetString("FolderDoesnTExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hotspot.
        /// </summary>
        public static string Hotspot {
            get {
                return ResourceManager.GetString("Hotspot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info and Language.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info and Options.
        /// </summary>
        public static string InfoAndOptions {
            get {
                return ResourceManager.GetString("InfoAndOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language: English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language: Español.
        /// </summary>
        public static string LanguageEspañol {
            get {
                return ResourceManager.GetString("LanguageEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Coord.
        /// </summary>
        public static string MouseCoord {
            get {
                return ResourceManager.GetString("MouseCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Properties.
        /// </summary>
        public static string MouseProperties {
            get {
                return ResourceManager.GetString("MouseProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New File (Ctrl+N).
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create new file.
        /// </summary>
        public static string NewFileTitle {
            get {
                return ResourceManager.GetString("NewFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next   🢖🢖.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open (Ctrl+O).
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open....
        /// </summary>
        public static string OpenTitle {
            get {
                return ResourceManager.GetString("OpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options:.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pixel Color.
        /// </summary>
        public static string PixelColor {
            get {
                return ResourceManager.GetString("PixelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PNG Files .
        /// </summary>
        public static string PNGFiles {
            get {
                return ResourceManager.GetString("PNGFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pply.
        /// </summary>
        public static string pply {
            get {
                return ResourceManager.GetString("pply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview Background.
        /// </summary>
        public static string PreviewBackground {
            get {
                return ResourceManager.GetString("PreviewBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redo (Ctrl+Y).
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save (Ctrl+S).
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select where the cursor will click.
        /// </summary>
        public static string SelectWhereTheCursorWillClick {
            get {
                return ResourceManager.GetString("SelectWhereTheCursorWillClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Switch Colors.
        /// </summary>
        public static string SwitchColors {
            get {
                return ResourceManager.GetString("SwitchColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undo (Ctrl+Z).
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You don&apos;t have this folder: &quot;C:\Windows\Cursors\- Pixie Cursors -&quot;. Try creating it or reinstall Pixie Cursors..
        /// </summary>
        public static string YouDonTHaveThisFolder {
            get {
                return ResourceManager.GetString("YouDonTHaveThisFolder", resourceCulture);
            }
        }
    }
}
